[build]
  publish = "build"
  command = "npm run build"

[[headers]]
for = "/*"
[headers.values]
  Content-Security-Policy = "default-src *; script-src *; style-src *; img-src *; connect-src *; frame-src *; object-src *; base-uri *;"
